baseURL = 'https://sig0lease.networkcommons.org/'
locale = 'en-us'
title = 'sig0lease'
theme = ["hugo-embed-pdf-shortcode", "gohugo-theme-ananke"]
enableInlineShortcodes = true
[params]
  subtitle = 'collaborative service discovery'
  toc = true
  # site_logo = "images/mycosystem-section-cut.jpg"
  [params.ananke]
    custom_css = ["custom.css"]
  [params.ananke.social.follow]
    networks = ["mastodon", "github"]
  [params.ananke.social.mastodon]
    profilelink = "https://hachyderm.io/@sig0lease"
  [params.ananke.social.github]
    profilelink = "https://github.com/networkcommons/sig0lease"
[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
    unsafe = true
[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
